input-files:
  - docs/Chapter-1.md
  - docs/Chapter-2.md
  - docs/Chapter-3.md
  - docs/Chapter-4.md
  - docs/Chapter-5.md

file-scope: true

resource-path: 
  - '.'
  - 'assets'
  - 'docs'

pdf-engine: xelatex

variables:
  geometry: [margin=1in, a4paper]
  graphics: true

# Esta regla ancla las imágenes exactamente donde las escribes en el texto
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{H}

toc: true
toc-depth: 3
number-sections: true

output-file: Reporte_Final_EcoRoad.pdf
