name: Generar PDF con Pandoc

on:
  push:
    branches: [ "main" ]

jobs:
  fabricar-documento:
    runs-on: ubuntu-24.04 
    steps:
      - name: 1. Descargar tus archivos de Markdown
        uses: actions/checkout@v4

      - name: 2. Instalar el programa Pandoc en el servidor
        uses: r-lib/actions/setup-pandoc@v3 
        with:
          pandoc-version: '3.1'

      - name: 3. Instalar el motor creador de PDF (LaTeX avanzado)
        # Instalamos xetex y paquetes recomendados para manejar imágenes complejas
        run: sudo apt-get update && sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-extra

      - name: 4. Unir todo y fabricar el PDF
        # Añadimos --pdf-engine=xelatex directamente aquí para forzar el motor más robusto
        run: pandoc --defaults=build.yaml --pdf-engine=xelatex

      - name: 5. Guardar el PDF para que lo puedas descargar
        uses: actions/upload-artifact@v4
        with:
          name: Archivo_PDF_EcoRoad
          path: Reporte_Final_EcoRoad.pdf
